version: '3'

services:
  app:
    build: .
    command: .docker/entrypoint.sh
    container_name: micro-videos-app-without-nest-typescript
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app